version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_URL: mysqlx://db:33060/your_database  # Using MySQL X Protocol
      DB_USER: your_username
      DB_PASSWORD: your_password

volumes:
  db_data:
