version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/your_database
      DB_USER: your_username
      DB_PASSWORD: your_password

volumes:
  db_data:
