version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mock_dataDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mock-data-app
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:mysql://db:3306/mock_dataDB"
      DB_USER: "root"
      DB_PASSWORD: "password"
    volumes:
      - ./target:/app
    command: ["java", "-jar", "MockDataGenerator.jar"]

volumes:
  db_data:
